//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDV_POE_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_carInspectorDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_carInspectorDriver()
        {
            this.tbl_rental = new HashSet<tbl_rental>();
        }
    
        public int CIDID { get; set; }
        public string carID { get; set; }
        public Nullable<int> inspectorID { get; set; }
        public Nullable<int> driverID { get; set; }
    
        public virtual tbl_car tbl_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rental> tbl_rental { get; set; }
        public virtual tbl_driver tbl_driver { get; set; }
        public virtual tbl_inspector tbl_inspector { get; set; }
    }
}
